/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type VideoAspectRatio = {
  width: number
  height: number
}

export type FileLink = {
  file?: FileLinkFile
  buttonText?: string
}

export type PbBlockMarqueeSettings = {
  speed: number
  direction?: 'left' | 'right'
  color?: 'text-body' | 'text-accent'
  imageSize: number
}

export type BlockWidths = {
  mobile?: 'grid-cols-1' | 'grid-cols-2' | 'grid-cols-3' | 'grid-cols-4'
  tablet?: 'md:grid-cols-1' | 'md:grid-cols-2' | 'md:grid-cols-3' | 'md:grid-cols-4'
  desktop?: 'lg:grid-cols-1' | 'lg:grid-cols-2' | 'lg:grid-cols-3' | 'lg:grid-cols-4'
}

export type Size = {
  mobile: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
  tablet: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
  desktop: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
}

export type Start = {
  mobile: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
  tablet: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
  desktop: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
}

export type BannerImage = {
  position?: 'offsetXY' | 'offsetX' | 'edge'
  image?: BannerImageImage
  imageMaskType?: 'none' | 'notches' | 'logoDB' | 'archIK' | 'archTT'
  imageCrop?: 0 | 1 | 0.8 | 0.6666666667 | 1.25 | 1.5 | 1.7777777778 | 2.5
  priority?: boolean
}

export type BackgroundImage = {
  image?: BackgroundImageImage
  imageMaskType?: 'none' | 'notches' | 'logoDB' | 'archIK' | 'archTT'
  imageCrop?: 0 | 1 | 0.8 | 0.6666666667 | 1.25 | 1.5 | 1.7777777778 | 2.5
  priority?: boolean
}

export type FeaturedImage = {
  image?: FeaturedImageImage
  imageMaskType?: 'none' | 'notches' | 'logoDB' | 'archIK' | 'archTT'
  imageCrop?: 0 | 1 | 0.8 | 0.6666666667 | 1.25 | 1.5 | 1.7777777778 | 2.5
  priority?: boolean
  bottomAlign?: boolean
}

export type Preheading = {
  color?: ColorChoice
  left?: string
  right?: string
}

export type ShapeWidth = {
  mobile?: number
  tablet?: number
  desktop?: number
}

export type StickyImages = {
  topLeft?: TopLeft
  topRight?: TopRight
  bottomLeft?: BottomLeft
  bottomRight?: BottomRight
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type DropdownThumbnail = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "dropdownThumbnail.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type FileLinkFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "media" in schema
  _type: 'file'
}

export type MarkDefsFileLinkFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "file.media" in schema
  _type: 'file'
}

export type JobFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "job.file.media" in schema
  _type: 'file'
}

export type ImageElementImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "imageElement.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type YAlignment = {
  mobile: 'self-start' | 'self-center' | 'self-end'
  tablet: 'inherit' | 'self-start' | 'self-center' | 'self-end'
  desktop: 'inherit' | 'self-start' | 'self-center' | 'self-end'
}

export type BannerImageImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "bannerImage.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type BackgroundImageImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "backgroundImage.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type FeaturedImageImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "featuredImage.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  notchFrame?: boolean
  _type: 'image'
}

export type NewsPostImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "newsPost.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type TopLeft = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "topLeft.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type TopRight = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "topRight.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type BottomLeft = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "bottomLeft.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type BottomRight = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "bottomRight.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type SocialLink = {
  _type: 'socialLink'
  icon?:
    | 'Facebook'
    | 'Github'
    | 'Instagram'
    | 'Linkedin'
    | 'Soundcloud'
    | 'Spotify'
    | 'Threads'
    | 'Tiktok'
    | 'Twitter'
    | 'YouTube'
  url?: string
}

export type Seo = {
  _type: 'seo'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  seoTitle?: string
  description?: string
  hideFromSearchEngines?: boolean
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PtSlim = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: Array<
    | {
        href?: string
        _type: 'link'
        _key: string
      }
    | {
        reference?: PageReference
        _type: 'internalLink'
        _key: string
      }
  >
  level?: number
  _type: 'block'
  _key: string
}>

export type PtSingle = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: Array<
    | {
        href?: string
        _type: 'link'
        _key: string
      }
    | {
        reference?: PageReference
        _type: 'internalLink'
        _key: string
      }
  >
  level?: number
  _type: 'block'
  _key: string
}>

export type PtItalic = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type PtBold = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type PtBody = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: 'bullet' | 'number'
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type PtBasic = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<
    | {
        href?: string
        _type: 'link'
        _key: string
      }
    | {
        reference?: PageReference
        _type: 'internalLink'
        _key: string
      }
    | {
        file?: MarkDefsFileLinkFile
        _type: 'fileLink'
        _key: string
      }
  >
  level?: number
  _type: 'block'
  _key: string
}>

export type PbValues = {
  _type: 'pbValues'
  sectionSettings?: PbSectionSettings
  colorSteps?: number
  values?: Array<{
    title?: string
    caption?: string
    _type: 'value'
    _key: string
  }>
}

export type PbTriptych = {
  _type: 'pbTriptych'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  triptychType?: 'still' | 'carouselSingles' | 'carouselGroups'
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type PbNews = {
  _type: 'pbNews'
  sectionSettings?: PbSectionSettings
  title?: string
  colorSteps?: number
  newsPosts?: Array<{
    title?: string
    caption?: string
    image?: NewsPostImage
    url?: string
    _type: 'newsPost'
    _key: string
  }>
  ctaButton?: PbBlockButton
}

export type PbTimeline = {
  _type: 'pbTimeline'
  sectionSettings?: PbSectionSettings
  rowWidth?: 12 | 10
  preheading?: string
  title?: string
  events?: Array<{
    year?: string
    heading?: string
    description?: PtBold
    image?: ObjectImage
    _key: string
  }>
}

export type PbSectionSettingsHero = {
  _type: 'pbSectionSettingsHero'
  enableSection?: boolean
  sectionId?: string
  topOrnament?: boolean
  sectionBgColor?: ColorChoice
  marginTop?: 1 | 2 | 3 | 4 | 5
  marginBottom?: 1 | 2 | 3 | 4 | 5
}

export type PbSectionSettings = {
  _type: 'pbSectionSettings'
  enableSection?: boolean
  sectionId?: string
  topOrnament?: boolean
  sectionBgColor?: ColorChoice
  marginTop?: 1 | 2 | 3 | 4 | 5
  marginBottom?: 1 | 2 | 3 | 4 | 5
}

export type PbSectionGroup = {
  _type: 'pbSectionGroup'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  stickyBackgroundImages?: boolean
  stickyImages?: StickyImages
  pbGroupSections?: Array<
    | ({
        _key: string
      } & PbGridSingle)
    | ({
        _key: string
      } & PbGridDouble)
    | ({
        _key: string
      } & PbGridMulti)
    | ({
        _key: string
      } & PbBanner)
    | ({
        _key: string
      } & PbImageWithCard)
    | ({
        _key: string
      } & PbFeature)
    | ({
        _key: string
      } & PbTriptych)
    | ({
        _key: string
      } & PbHeroShape)
    | ({
        _key: string
      } & PbHeroBrand)
    | ({
        _key: string
      } & PbHeroHome)
    | ({
        _key: string
      } & PbTimeline)
    | ({
        _key: string
      } & PbNews)
    | ({
        _key: string
      } & PbValues)
  >
}

export type PbSections = Array<
  | ({
      _key: string
    } & PbGridSingle)
  | ({
      _key: string
    } & PbGridDouble)
  | ({
      _key: string
    } & PbGridMulti)
  | ({
      _key: string
    } & PbBanner)
  | ({
      _key: string
    } & PbImageWithCard)
  | ({
      _key: string
    } & PbFeature)
  | ({
      _key: string
    } & PbTriptych)
  | ({
      _key: string
    } & PbHeroShape)
  | ({
      _key: string
    } & PbHeroBrand)
  | ({
      _key: string
    } & PbHeroHome)
  | ({
      _key: string
    } & PbTimeline)
  | ({
      _key: string
    } & PbNews)
  | ({
      _key: string
    } & PbValues)
  | ({
      _key: string
    } & PbSectionGroup)
>

export type PbImageWithCard = {
  _type: 'pbImageWithCard'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  size?: 6 | 8
  cardColor?: ColorChoice
  backgroundImage?: BackgroundImage
  pbBlocks?: PbBlocks
  spaceBetweenBlocks?:
    | 'gap-0'
    | 'gap-gut-25'
    | 'gap-gut-50'
    | 'gap-gut'
    | 'gap-gut-150'
    | 'gap-gut-200'
}

export type PbGridDouble = {
  _type: 'pbGridDouble'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  rowWidth?: 12 | 10 | 8 | 6
  columnProportions?: '50-50' | '60-40' | '40-60'
  yAlignment?: 'items-start' | 'items-center' | 'items-end'
  columnOne?: Column
  columnTwo?: Column
}

export type PbGridSingle = {
  _type: 'pbGridSingle'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  rowWidth?: 12 | 10 | 8 | 6
  bgLogoShape?: boolean
  revealEffect?: 'none' | 'stagger' | 'fade-up' | 'fade-right'
  pbBlocks?: PbBlocks
  centerBlocks?: boolean
  spaceBetweenBlocks?:
    | 'gap-0'
    | 'gap-gut-25'
    | 'gap-gut-50'
    | 'gap-gut'
    | 'gap-gut-150'
    | 'gap-gut-200'
  blockWidths?: BlockWidths
}

export type PbGridMulti = {
  _type: 'pbGridMulti'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  rowWidth: 12 | 10 | 8 | 6
  columns?: Array<{
    columnSettings?: PbColSettings
    yAlignment?: YAlignment
    revealEffect?: 'none' | 'stagger' | 'fade-up' | 'fade-right'
    pbBlocks?: PbBlocks
    centerBlocks?: boolean
    spaceBetweenBlocks?:
      | 'gap-0'
      | 'gap-gut-25'
      | 'gap-gut-50'
      | 'gap-gut'
      | 'gap-gut-150'
      | 'gap-gut-200'
    blockWidths?: BlockWidths
    _key: string
  }>
}

export type PbHeroHome = {
  _type: 'pbHeroHome'
  sectionSettings?: PbSectionSettingsHero
  heading?: PtItalic
  imagesPrepNote?: Note
  imagesTop1?: ImageCycle
  imagesTop2?: ImageCycle
  imagesBottom1?: ImageCycle
  imagesBottom2?: ImageCycle
  imagesBottom3?: ImageCycle
}

export type BrandsReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brands'
}

export type PbHeroBrand = {
  _type: 'pbHeroBrand'
  sectionSettings?: PbSectionSettingsHero
  brand: BrandsReference
  shapeWidth?: ShapeWidth
  introductionText?: string
  bgImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  fgColorTop?: ColorChoice
  bgColorBottom?: ColorChoice
  fgColorBottom?: ColorChoice
}

export type PbHeroShape = {
  _type: 'pbHeroShape'
  sectionSettings?: PbSectionSettingsHero
  showPreheading?: boolean
  preheading?: Preheading
  backdropType?: 'image' | 'video' | 'color'
  backdropColor?: ColorChoice
  backdropImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  backdropVideo?: MuxVideo
  backdropPosition?:
    | 'top left'
    | 'top center'
    | 'top right'
    | 'center left'
    | 'center center'
    | 'center right'
    | 'bottom left'
    | 'bottom center'
    | 'bottom right'
  contentOverlay?: 'none' | 'headingLogos' | 'stickyLogo'
  heading?: PtItalic
  subbrandLogos?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
}

export type PbFeature = {
  _type: 'pbFeature'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  rowWidth?: 12 | 10
  cardColor?: ColorChoice
  featuredImage?: FeaturedImage
  pbBlocks?: PbBlocks
  spaceBetweenBlocks?:
    | 'gap-0'
    | 'gap-gut-25'
    | 'gap-gut-50'
    | 'gap-gut'
    | 'gap-gut-150'
    | 'gap-gut-200'
}

export type PbColSettings = {
  _type: 'pbColSettings'
  size?: Size
  start?: Start
  accordionMode?: boolean
  accordionTitle?: string
}

export type PbBlockVideoEmbed = {
  _type: 'pbBlockVideoEmbed'
  videoEmbedUrl?: string
  videoAspectRatio?: VideoAspectRatio
}

export type PbBlockText = {
  _type: 'pbBlockText'
  textContent?: PtBasic
}

export type PbBlockPlainText = {
  _type: 'pbBlockPlainText'
  textStyle: 'ts-body' | 'ts-serif' | 'ts-sans-tall' | 'ts-sans-wide'
  textSize?: 'ts-p-lg' | 'ts-p-md' | 'ts-p-sm' | 'ts-p-xs'
  textSizeSerif?: 'ts-h1' | 'ts-h2' | 'ts-h3' | 'ts-h4'
  textSizeSans?: 'ts-h5' | 'ts-h6'
  textContent?: string
  textContentRich?: PtItalic
  textAlign?: 'text-left' | 'text-center' | 'text-right'
  textColor?: ColorChoice
  balanceLines?: boolean
}

export type PbBlockJobs = {
  _type: 'pbBlockJobs'
  jobs?: Array<{
    title?: string
    company?: BrandsReference
    subtitle?: string
    description?: string
    linkType?: 'externalLink' | 'file'
    url?: string
    file?: JobFile
    _type: 'job'
    _key: string
  }>
}

export type PbBlockMarquee = {
  _type: 'pbBlockMarquee'
  settings?: PbBlockMarqueeSettings
  elements?: Array<
    | {
        text?: string
        style?:
          | 'ts-h1'
          | 'ts-h2'
          | 'ts-h3'
          | 'ts-h4'
          | 'ts-p-lg'
          | 'ts-p-md'
          | 'ts-p-sm'
          | 'ts-p-xs'
          | 'ts-h5'
          | 'ts-h6'
        _type: 'textElement'
        _key: string
      }
    | {
        image?: ImageElementImage
        altText?: string
        imageCrop?: 0 | 1 | 0.8 | 0.6666666667 | 1.25 | 1.5 | 1.7777777778 | 2.5
        roundedCorners?: boolean
        invertColor?: boolean
        blendModeLighten?: boolean
        _type: 'imageElement'
        _key: string
      }
  >
}

export type PbBlockDivider = {
  _type: 'pbBlockDivider'
  showOnMobile?: boolean
  showOnTablet?: boolean
  showOnDesktop?: boolean
  showDividerLine?: boolean
  showOrnament?: boolean
  size?: 1 | 2 | 3 | 4 | 5
}

export type PbBlocks = Array<
  | ({
      _key: string
    } & PbBlockPlainText)
  | ({
      _key: string
    } & PbBlockImage)
  | ({
      _key: string
    } & PbBlockVideoEmbed)
  | ({
      _key: string
    } & PbBlockButton)
  | ({
      _key: string
    } & PbBlockButtonMulti)
  | ({
      _key: string
    } & PbBlockDivider)
  | ({
      _key: string
    } & PbBlockText)
  | ({
      _key: string
    } & PbBlockJobs)
  | ({
      _key: string
    } & PbBlockMarquee)
>

export type PbBlockButtonMulti = {
  _type: 'pbBlockButtonMulti'
  buttons: Array<
    {
      _key: string
    } & PbBlockButton
  >
}

export type PbBlockButton = {
  _type: 'pbBlockButton'
  linkType?: 'sitePage' | 'externalLink' | 'file'
  sitePage?: NavPage
  externalLink?: NavExternal
  fileLink?: FileLink
  icon?:
    | 'none'
    | 'arrow'
    | 'Facebook'
    | 'Github'
    | 'Instagram'
    | 'Linkedin'
    | 'Soundcloud'
    | 'Spotify'
    | 'Threads'
    | 'Tiktok'
    | 'Twitter'
    | 'YouTube'
  arrowDirection?: 'up' | 'right' | 'down' | 'left'
  buttonStyle?: 'default' | 'outline' | 'no-bg'
  buttonColor?: ColorChoice
}

export type PbBlockImage = {
  _type: 'pbBlockImage'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imageMaskType?: 'none' | 'notches' | 'logoDB' | 'archIK' | 'archTT'
  imageCrop?: 0 | 1 | 0.8 | 0.6666666667 | 1.25 | 1.5 | 1.7777777778 | 2.5
  imageWidth?: number
  caption?: string
  priority?: boolean
}

export type PbBanner = {
  _type: 'pbBanner'
  sectionSettings?: PbSectionSettings
  sectionName?: string
  bannerDirection?: 'ltr' | 'rtl'
  bgColor?: ColorChoice
  bannerImage?: BannerImage
  pbBlocks?: PbBlocks
  spaceBetweenBlocks?:
    | 'gap-0'
    | 'gap-gut-25'
    | 'gap-gut-50'
    | 'gap-gut'
    | 'gap-gut-150'
    | 'gap-gut-200'
}

export type HomeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'home'
}

export type NavPage = {
  _type: 'navPage'
  title?: string
  page?: HomeReference | PageReference
  anchorLink?: string
}

export type NavLinks = {
  _type: 'navLinks'
  navItems?: Array<
    | ({
        _key: string
      } & NavPage)
    | ({
        _key: string
      } & NavExternal)
  >
}

export type NavExternal = {
  _type: 'navExternal'
  title?: string
  url?: string
}

export type ImageCycle = {
  _type: 'imageCycle'
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  altText?: string
}

export type Dropdown = {
  _type: 'dropdown'
  title?: string
  items?: Array<
    | {
        title?: string
        page?: HomeReference | PageReference
        anchorLink?: string
        subtitle?: string
        dropdownThumbnail?: DropdownThumbnail
        _type: 'dropdownPage'
        _key: string
      }
    | {
        title?: string
        url?: string
        subtitle?: string
        dropdownThumbnail?: DropdownThumbnail
        _type: 'dropdownExternal'
        _key: string
      }
  >
}

export type ColorChoice = {
  _type: 'colorChoice'
  colorType?: 'none' | 'semitransparent' | 'dark' | 'light' | 'gradient' | 'custom'
  gradientNote?: Note
  colorDark?:
    | '--color-blue-800'
    | '--color-blue-700'
    | '--color-blue-650'
    | '--color-teal'
    | '--color-logo-red'
    | '--color-ik-red'
    | '--color-tt-pink'
    | '--color-tt-teal'
    | '--color-saffron-600'
    | '--color-chili-600'
    | '--color-tumeric-600'
    | '--color-lime-600'
    | '--color-lotus-600'
  colorLight?:
    | '--color-offwhite'
    | '--color-blue-200'
    | '--color-saffron-200'
    | '--color-chili-200'
    | '--color-tumeric-200'
    | '--color-lime-200'
    | '--color-lotus-200'
  colorCustom?: Color
}

export type Column = {
  _type: 'column'
  revealEffect?: 'none' | 'stagger' | 'fade-up' | 'fade-right'
  pbBlocks?: PbBlocks
  centerBlocks?: boolean
  spaceBetweenBlocks?:
    | 'gap-0'
    | 'gap-gut-25'
    | 'gap-gut-50'
    | 'gap-gut'
    | 'gap-gut-150'
    | 'gap-gut-200'
  blockWidths?: BlockWidths
}

export type Redirect = {
  _id: string
  _type: 'redirect'
  _createdAt: string
  _updatedAt: string
  _rev: string
  deployNote?: Note
  fromPath: string
  toPath: string
  permanent?: boolean
}

export type Note = string

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  mainNavLeft?: Array<
    | ({
        _key: string
      } & NavPage)
    | ({
        _key: string
      } & NavExternal)
    | ({
        _key: string
      } & Dropdown)
  >
  mainNavRight?: Array<
    | ({
        _key: string
      } & NavPage)
    | ({
        _key: string
      } & NavExternal)
    | ({
        _key: string
      } & Dropdown)
  >
  showHeaderSocials?: boolean
  showHeaderCTAs?: boolean
  headerCTAs?: Array<
    {
      _key: string
    } & PbBlockButton
  >
  contactEmail?: string
  socialIcons?: Array<
    {
      _key: string
    } & SocialLink
  >
  badges?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    link?: string
    alt?: string
    _type: 'image'
    _key: string
  }>
  footerNav?: NavLinks
  footerNav2?: NavLinks
  footerBrands?: Array<
    {
      _key: string
    } & BrandsReference
  >
  seo?: Seo
  googletagmanagerID?: string
  customScripts?: Array<{
    name?: string
    script?: string
    category: 'necessary' | 'analytics' | 'marketing'
    _type: 'customScript'
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  pbSections?: PbSections
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  pbSections?: PbSections
  seo?: Seo
}

export type MuxVideoAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'mux.videoAsset'
}

export type MuxVideo = {
  _type: 'mux.video'
  asset?: MuxVideoAssetReference
}

export type Brands = {
  _id: string
  _type: 'brands'
  _createdAt: string
  _updatedAt: string
  _rev: string
  brandsNote?: Note
  title?: string
  websiteLink?: NavExternal
  socialIcons?: Array<
    {
      _key: string
    } & SocialLink
  >
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bgShape?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MuxVideoAsset = {
  _id: string
  _type: 'mux.videoAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  status?: string
  assetId?: string
  playbackId?: string
  filename?: string
  thumbTime?: number
  data?: MuxAssetData
}

export type MuxAssetData = {
  _type: 'mux.assetData'
  resolution_tier?: string
  upload_id?: string
  created_at?: string
  id?: string
  status?: string
  max_stored_resolution?: string
  passthrough?: string
  encoding_tier?: string
  video_quality?: string
  master_access?: string
  aspect_ratio?: string
  duration?: number
  max_stored_frame_rate?: number
  mp4_support?: string
  max_resolution_tier?: string
  tracks?: Array<
    {
      _key: string
    } & MuxTrack
  >
  playback_ids?: Array<
    {
      _key: string
    } & MuxPlaybackId
  >
  static_renditions?: MuxStaticRenditions
}

export type MuxStaticRenditions = {
  _type: 'mux.staticRenditions'
  status?: string
  files?: Array<
    {
      _key: string
    } & MuxStaticRenditionFile
  >
}

export type MuxStaticRenditionFile = {
  _type: 'mux.staticRenditionFile'
  name?: string
  ext?: string
  height?: number
  width?: number
  bitrate?: number
  filesize?: string
  type?: string
  status?: string
  resolution_tier?: string
  resolution?: string
  id?: string
  passthrough?: string
}

export type MuxPlaybackId = {
  _type: 'mux.playbackId'
  id?: string
  policy?: string
}

export type MuxTrack = {
  _type: 'mux.track'
  id?: string
  type?: string
  max_width?: number
  max_frame_rate?: number
  duration?: number
  max_height?: number
  language_code?: string
  name?: string
  status?: string
  text_source?: string
  text_type?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | VideoAspectRatio
  | FileLink
  | PbBlockMarqueeSettings
  | BlockWidths
  | Size
  | Start
  | BannerImage
  | BackgroundImage
  | FeaturedImage
  | Preheading
  | ShapeWidth
  | StickyImages
  | SanityImageAssetReference
  | DropdownThumbnail
  | SanityFileAssetReference
  | FileLinkFile
  | MarkDefsFileLinkFile
  | JobFile
  | ImageElementImage
  | YAlignment
  | BannerImageImage
  | BackgroundImageImage
  | FeaturedImageImage
  | ObjectImage
  | NewsPostImage
  | TopLeft
  | TopRight
  | BottomLeft
  | BottomRight
  | SocialLink
  | Seo
  | PageReference
  | PtSlim
  | PtSingle
  | PtItalic
  | PtBold
  | PtBody
  | PtBasic
  | PbValues
  | PbTriptych
  | PbNews
  | PbTimeline
  | PbSectionSettingsHero
  | PbSectionSettings
  | PbSectionGroup
  | PbSections
  | PbImageWithCard
  | PbGridDouble
  | PbGridSingle
  | PbGridMulti
  | PbHeroHome
  | BrandsReference
  | PbHeroBrand
  | PbHeroShape
  | PbFeature
  | PbColSettings
  | PbBlockVideoEmbed
  | PbBlockText
  | PbBlockPlainText
  | PbBlockJobs
  | PbBlockMarquee
  | PbBlockDivider
  | PbBlocks
  | PbBlockButtonMulti
  | PbBlockButton
  | PbBlockImage
  | PbBanner
  | HomeReference
  | NavPage
  | NavLinks
  | NavExternal
  | ImageCycle
  | Dropdown
  | ColorChoice
  | Column
  | Redirect
  | Note
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Home
  | Page
  | MuxVideoAssetReference
  | MuxVideo
  | Brands
  | Slug
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
